language:
	- c++

before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -y libuuid-dev ceph-dev boost-dev cmake

branches:
  only:
	- travis

os:
	- linux

compiler:
	- clang
	- g++

script: mkdir build; cd buid; cmake .. -DCMAKE_BUILD_TYPE=Release
